server:
  port: 8080
spring:
  application:
    name: wxy-cloud-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:

        - id: wxy-cloud-admin
          uri: lb://wxy-cloud-admin
          order: 1
          predicates:
            - Path=/share-admin-api/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: wxy-cloud-user
          uri: lb://wxy-cloud-user
          order: 2
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: wxy-cloud-content
          uri: lb://wxy-cloud-content
          order: 3
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
        - id: wxy-cloud-iot
          uri: lb://wxy-cloud-iot
          order: 4
          predicates:
            - Path=/iot/**
          filters:
            - StripPrefix=1
          metadata:
            websocket: true
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE